### PR TITLE
Implement styling

### PR DESCRIPTION
**Pull request by amentetteh**
### Project requirements

- You will find all the details of the Bookstore design in [Zeplin](https://zeplin.io/).
- [Login to Zeplin](https://app.zeplin.io/login) (hint: you will find the credentials in the [sneak peek](./sneak_peek_v2_0.md) of the project).
- Open the project *Bookstore CMS*.
- Add any missing JSX elements to your projects (without adding extra functionality)
- You may use the CSS rules detailed in Zeplin to style the website.
- Your final design should match Zeplin's design (this includes all elements + the same styling)

### CODE REVIEW

**Review by franclobo — COMMENTED** [review]
Hi @amentetteh, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by amentetteh** [comment]
@franclobo, thanks very much. Errors fixed. Can you then review it for me ?

**Comment by franclobo** [comment]
Hello @amentetteh maybe another code reviewer will review your project when you submit it again.

**Comment by bellom** [comment]
@amentetteh 

### This is a manual review

# Approved

Cheers and Happy coding!

**Pull request merged**
